### ISSUE TITLE
Protect app and permissions with PIN/Passphrase

### ISSUE THREAD

**Issue by ciori** [greenart7c3/Amber#10]
It would be nice to have the ability to protect the app, permissions, event signing and private key with a PIN or passphrase that is requested (for example) when the application opens up to be able to sign stuff.

Then, just as an idea for a future enhancement, there could be a plausible deniability feature so that a secondary/fake nostr account will be loaded when the user enters a specific/wrong PIN or Passphrase.

**Comment by kehiy** [comment]
@greenart7c3 I think this is fixed now.

**Comment by ciori** [comment]
Would love to see the ability to use a PIN/passphrase instead of the system fingerprint unlock.

**Comment by greenart7c3** [comment]
Sorry for taking this long, it will be available in the next release
