### ISSUE TITLE
Example of uri scheme string to sign via QRcode scan.

### ISSUE THREAD

**Issue by ildella** [greenart7c3/Amber#11]
I would like to display the QR Code from a string to let user scan it, open Amber and sign. 

When user is on mobile browser, I can just redirect `href=intent:${encodedJson}....` as explained in the doc and it works. 

When user is on Desktop I want to display a QR code so that scanned from mobile it will invoke Amber on the device. 
Obviously the same `intent:...` string does not work and I can't figure out what is the string that is built. 

Would you add an example of that? 

Thanks

**Comment by greenart7c3** [comment]
You will need to use nostrsigner:// but the app is not ready to use this and is crashing
How will the user get the response back to the pc or you will use the callbackurl?
