### ISSUE TITLE
Keeps crashing warning when using camera

### ISSUE THREAD

**Issue by maridonkers** [greenart7c3/Amber#110]
Android phone
```
Galaxy M13
Model name: SM-M135F/DSN
```

If start my camera app (stock Android) then I get a warning that Amber keeps crashing with a close app option.

Amber app is configured without camera permission (don't use that functionality)

**Comment by greenart7c3** [comment]
Cant reproduce here. your camera should not be talking to any nostr apps.
Are you using any web clients?
do you have any space left in your device?
Are you scanning a qr code with  your camera app?

**Comment by greenart7c3** [comment]
Is this still happening in the latest version?
