### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [greenart7c3/Amber#114]
The tag name is v.1.3.6 which should be v1.3.6. Could you please fix it? Thanks!

**Comment by greenart7c3** [comment]
Done. Sorry about that

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
@greenart7c3 no fdroid APK for 2.0.6? ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/8085503100#L970

**Comment by greenart7c3** [comment]
Damm, I think I deleted the wrong file. I'll see if I can fix this when I get home

**Comment by greenart7c3** [comment]
Can you try again to see if it is fixed?

**Comment by licaon-kter** [comment]
yup, confirmed, thanks
