### ISSUE TITLE
Question: How to use Amber to connect Ditto to a Mastodon app?

### ISSUE THREAD

**Issue by xronin01** [greenart7c3/Amber#115]
![Screenshot_20240903-153551_Mastodon](https://github.com/user-attachments/assets/aac992eb-d0d0-4269-bfa4-484542de7a29)
![Screenshot_20240903-153512_Fennec](https://github.com/user-attachments/assets/72aff70f-9327-4529-b611-e71ea92bb0a8)
https://ditto.pub/
https://soapbox.pub/ditto/

**Comment by greenart7c3** [comment]
https://github.com/user-attachments/assets/7b4b4da7-130e-47c6-a4c6-9b40a40dbba7

**Comment by xronin01** [comment]
the Amber notification does not appear

**Comment by greenart7c3** [comment]
Did you setup ntfy?
Try changing the notification type in settings to connect directly to relay

**Comment by xronin01** [comment]
https://github.com/user-attachments/assets/9f16185a-d114-4412-be29-979d7d178560

**Comment by xronin01** [comment]
![Screenshot_20240903-171408_Amber](https://github.com/user-attachments/assets/043a0b2a-2cf3-44d5-986b-188ed033764f)

**Comment by greenart7c3** [comment]
After changing the relay copy the bunker url again
Check the logs in settings.
I think someone had problems with the distributor you are using.
Can you try ntfy?

**Comment by xronin01** [comment]
it worked with ntfy, thanks!

**Comment by greenart7c3** [comment]
You welcome.
I'll check if I can find why gcompat is not working

**Comment by greenart7c3** [comment]
Do you use play services on your device?
gcompat needs google play services to work, I think that was the problem

**Comment by xronin01** [comment]
I have google play services

**Comment by greenart7c3** [comment]
Fixed it in version 1.3.7
