### ISSUE TITLE
Hi, option to login using Amber using PC

### ISSUE THREAD

**Issue by bitcoinuser** [greenart7c3/Amber#119]
Hi,

I see that on npub.pro on PC, I see Amber login option. I would like to know if is possible for example on PC, login with Amber, so the npub.pro shows a qrcode, I read it with Amber, so the interactions that needs permission on PC, shows on Amber to be approved or denied. Understand? Thanks

**Comment by greenart7c3** [comment]
In npub.pro you need to go connect -> advanced > connection string
In amber go to permissions > connect app and read the qrcode

**Comment by bitcoinuser** [comment]
> In npub.pro you need to go connect -> advanced > connection string In amber go to permissions > connect app and read the qrcode

I learned but I was unable to login on satcom.app extension

![Captura de tela de 2024-09-08 13-40-34](https://github.com/user-attachments/assets/1f22e96b-a527-4471-a99f-cb65841ec340)

**Comment by bitcoinuser** [comment]
I was able to login now, thanks.
