### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by RasheedAZ** [greenart7c3/Amber#12]
Hi. Thanks for creating this useful app. Are you open to it being submitted to F-Droid?

If you support reproducible builds, I think that simplifies the process. 

https://reproducible-builds.org/

**Comment by greenart7c3** [comment]
Thanks, will look into making it reproducible

**Comment by greenart7c3** [comment]
I think the latest pre release is reproducible now. Can you test it?
Would make some documentation on how to compile help too?
like [signal](https://github.com/signalapp/Signal-Android/tree/main/reproducible-builds) does.
I also created some build flavors now because i needed push notifications for a feature, so for fdroid you should use the free flavor

```Kotlin
./gradlew clean assembleFreeRelease
```

**Comment by RasheedAZ** [comment]
I was trying to test amber-free-arm64-v8a-v1.0.6.apk 

How is this meant to work? Is a popup supposed to show up when trying to login to a client or post a note?

Does it need any permissions other than notifications?

**Comment by greenart7c3** [comment]
You can download [amethyst](https://github.com/vitorpamplona/amethyst/releases) and when login in there's a login with amber button
To test web clients you can use nostrudel.ninja and in the login there's an advanced option and there's a nostr connect/bunker button
Before using nostrudel go to amber in the permissions screen press the new app button and copy the bunker url into noStrudel webpage. This will show a notification to connect to noStrudel

**Comment by RasheedAZ** [comment]
Oh ok never saw that on Amethyst as I've never logged out or used another profile. Just tested successfully on Amethyst. Will try a web client now

**Comment by RasheedAZ** [comment]
> This will show a notification to connect to noStrudel

This notification didn't show so I just went back and clicked "Use Amber" and it worked.

**Comment by licaon-kter** [comment]
you tagged https://github.com/greenart7c3/Amber/tree/v1.1.0-pre1 but its versionName does not match the tag name https://github.com/greenart7c3/Amber/blob/v1.1.0-pre1/app/build.gradle#L19

so when F-Droid tries to build it and find its reproducible APK... it can't https://gitlab.com/fdroid/fdroiddata/-/jobs/7263225161#L467

do you want prereleases built?

**Comment by greenart7c3** [comment]
I think there's no need for pre release in fdroid, can you filter this?

**Comment by licaon-kter** [comment]
we can, but you need to decide on a pattern and stick to it

how shall we recognize prereleases exactly?

**Comment by greenart7c3** [comment]
I use 1.2.3-pre$number you can ignore the ones with -pre and pick only when there's only 1.2.3

**Comment by licaon-kter** [comment]
done https://gitlab.com/fdroid/fdroiddata/-/commit/ef0912f1d52a1f3531e0674b9341167ba07cdeee
