### ISSUE TITLE
Segfault when calling sign_event using the Content Resolver as per NIP-55

### ISSUE THREAD

**Issue by chebizarro** [greenart7c3/Amber#127]
Hey there,

I came across this issue when developing the [Capacitor plugin for NIP-55](https://github.com/chebizarro/nostr-signer-capacitor-plugin). Whenever I call the `sign_event` with an incomplete Event (no sig field) using Intents it works as expected but if I do the same using the Content Resolver it causes a segfault.

This is because the IntentUtils deserializes the event using the `getUnsignedEvent()` function which in turn calls `AmberEvent.toEvent()` which uses Safe Calls to access the event fields:

https://github.com/greenart7c3/Amber/blob/e316832532771af411a43ac1a47db039d4842333/app/src/main/java/com/greenart7c3/nostrsigner/service/IntentUtils.kt#L478

Whereas the Signer Provider uses the `Event.fromJSON()` function from the `com.vitorpamplona.quartz.events.Event` package, which causes a segfault if the event is missing any fields.

https://github.com/greenart7c3/Amber/blob/e316832532771af411a43ac1a47db039d4842333/app/src/main/java/com/greenart7c3/nostrsigner/SignerProvider.kt#L118

My workaround for the plugin was to put the Content Resolver calls in a Try...Catch block and fall back to using Intents if it failed and on the calling side from Coracle I made sure that I passed an event with the sig field.

I'm not sure what the expected behavior is or should be and the NIP doesn't specify it but I would think that it should be consistent between Intents and the Content Resolver. 

I'll work up a PR in the next couple of days, but wanted to raise the issue here so I don't forget again...

**Comment by greenart7c3** [comment]
Thanks for reporting. I believe it should use the getUnsignedEvent in the signerProvider

**Comment by greenart7c3** [comment]
I made some changes, now im using safe calls from amber event and checking the id hash and pubkey

**Comment by chebizarro** [comment]
This fixes the segfault issue I was having and the behavior now matches what a NIP-55 caller would expect (returns a signed event with hash as id). I'm going to close the issue now, thanks!
