### ISSUE TITLE
Editing the default relay only seems to connect to wss://relay.nsec.app.

### ISSUE THREAD

**Issue by TsukemonoGit** [greenart7c3/Amber#136]
Editing the default relay only seems to connect to wss://relay.nsec.app.

The local relay logs do not appear to be connected.

![](https://share.yabu.me/84b0c46ab699ac35eb2ca286470b85e081db2087cdef63932236c397417782f5/4f32e2c048fdb5e45c808ac4dd71386f9cecd43fee7650efb1a1897c4dcb78d5.webp)
![](https://share.yabu.me/84b0c46ab699ac35eb2ca286470b85e081db2087cdef63932236c397417782f5/9cf988f32a0b29bb6690f4dfd1d1b004212603af72370eb810c7e9ff9f71fc6b.webp)

amber v2.0.8-free

**Comment by greenart7c3** [comment]
Fixed in version 3
