### ISSUE TITLE
Support mnemonic seed phrase

### ISSUE THREAD

**Issue by dluvian** [greenart7c3/Amber#15]
If I will ever change my npub or have to create a new nostr account I would like it to be derived from a mnemonic seed phrase. My new app also generates a seed phrase instead of a single nsec. It would be nice if users could migrate it to Amber so they can reuse it for other apps.

Related nip: https://github.com/nostr-protocol/nips/blob/master/06.md

**Comment by dluvian** [comment]
https://nosta.me/ also uses mnemonics

**Comment by greenart7c3** [comment]
Added in the latest beta release
