### ISSUE TITLE
Change return of get_public_key(NIP-55) from npub to hex

### ISSUE THREAD

**Issue by Anderson-Juhasc** [greenart7c3/Amber#158]
When I run this URI nostrsigner:?compressionType=none&returnType=signature&type=get_public_key returns a npub, could be better if returns a public key as hex instead of npub to following the NIP-7.

**Comment by greenart7c3** [comment]
Fixed in 225cba295b295b312bb26114956a55ae839e2c3d
it will be available in the next release
