### ISSUE TITLE
webapp flow questions

### ISSUE THREAD

**Issue by jeremyd** [greenart7c3/Amber#2]
running version 0.0.3

Spent some time attempting to use amber from a webapp, here's what I found.  I have adb logcat running to see the error is my event does not have an ID.  The webapp does not know the pubkey of the user (without the user pasting this as an additional step for them) and therefor cannot serialize to provide the event ID.  I think the Amber intent should handle generating the ID since it is the one doing the signing and has the pubkey and the private key available.  The json ideally would only have to include kind, created_at, tags, and content.

(the error I get is: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference at com.greenart7c3.nostrsigner.service.model.Event$EventDeserializer.deserialize(Event.kt:201)

I've also realized, I will still need to be able to receive the signed event back from Amber, which I think would be possible if I setup my webapp as a PWA and use web share target.
https://developer.chrome.com/articles/web-share-target/

All in all, this is cool.  Logins are hard.  Let me know what you think about the ID situation and whether or not you think amber could share back the signed event.  Thanks

**Comment by jeremyd** [comment]
an example of the event i'm attempting to sign, in stringified json is: {"kind":27235,"created_at":1691188677,"tags":[],"content":"5NdAcSy9mSIMnOktXpmd"}

**Comment by greenart7c3** [comment]
Fixed the error deserializing the json and created a copy raw json button.
Will look into the web share target in the future

**Comment by greenart7c3** [comment]
https://github.com/greenart7c3/Amber/releases/tag/v0.0.5

**Comment by jeremyd** [comment]
Thank you!  I haven't had a chance to try it yet, but I want to close this issue so it doesn't clog the repo.  PV
