### ISSUE TITLE
What clients are supported?

### ISSUE THREAD

**Issue by dipunm** [greenart7c3/Amber#3]
I am using amethyst.
I also use brave browser.

What applications integrate with this app?

**Comment by greenart7c3** [comment]
None yet. I'm implementing on amethyst
Don't know if anyone is implementing on a web client yet

**Comment by dipunm** [comment]
Cool, I'll keep an eye out, curious to how this will look and feel.

**Comment by dipunm** [comment]
Using in amethyst. This is closed now 😁
