### ISSUE TITLE
Can't add an existing nsec

### ISSUE THREAD

**Issue by ildella** [greenart7c3/Amber#6]
Hi. Trying to import an existing nsec into Amber 0.5.1

Account
Add Account
Paste the nsec and click login

It goes back to the original screen and no new account is added. 

Am I doing something wrong? 
Amber already has one account, generated by itself.

**Comment by greenart7c3** [comment]
It worked for me. 
Are you using nsec or hex?
Can you share what device you are using?

**Comment by ildella** [comment]
Nsec

It's a motorola edge 30 with android 13

Yeah I bet it's a weird behavior.. It failed both 0.5.0 and 0.5.1

I'll try again tomorrow... One never knows :)

**Comment by ildella** [comment]
Obviously, my bad: I was adding an account that was already there :)
