### ISSUE TITLE
Review "Could not decrypt the message" 

### ISSUE THREAD

**Issue by vitorpamplona** [greenart7c3/Amber#65]
The error message is returned when Amber fails to decrypt. It happens when two accounts are logged in: an Amber-signing one and a pubkey-only one. Amethyst will try to decrypt the wrong account and Amber replies with a String "Could not decrypt the message", which could happen to be the encrypted message. 

I think this IF is the culprit. It's not a NIP04 encryption call: 
https://github.com/greenart7c3/Amber/blob/2117f8557e6212dc1f6ea7b3af7f1ba59188b561/app/src/main/java/com/greenart7c3/nostrsigner/SignerProvider.kt#L300

**Comment by greenart7c3** [comment]
fixed in https://github.com/greenart7c3/Amber/commit/698831772b613522ccc43734e39c14f09c3e00d1
