### ISSUE TITLE
Separate authorization page

### ISSUE THREAD

**Issue by water783** [greenart7c3/Amber#7]
Is it possible to have a separate authorization page, for example, when a client logs in, they are redirected to an Amber page to authorize signing, NIP4/NIP44 encryption/decryption, and no further authorization is required for subsequent operations?

**Comment by greenart7c3** [comment]
In the login page you can send some default permissions to be authorized for ever and the user can press the adjust button to deny and authorize manually. 
I forgot to update the docs but you need to send in the intent an array of objects

The object contains the type of the event and the kind

```kotlin

        val permissions = listOf(
            Permission(
                "sign_event",
                22242
            ),
            Permission(
                "nip04_encrypt"
            ),
            Permission(
                "nip04_decrypt"
            ),
            Permission(
                "nip44_encrypt"
            ),
            Permission(
                "nip44_decrypt"
            ),
            Permission(
                "decrypt_zap_event"
            ),
        )
```

**Comment by water783** [comment]
Great, thx :)

**Comment by greenart7c3** [comment]
Here's some screenshots:

![Screenshot_20231127_114038](https://github.com/greenart7c3/Amber/assets/115044884/b0984f53-ea9b-4905-9880-709615d323fa)

![Screenshot_20231127_114111](https://github.com/greenart7c3/Amber/assets/115044884/21e57a5e-78ab-4ac0-8cee-a174b555ed46)
