### ISSUE TITLE
Does not connect to relay when Push Notifications selected

### ISSUE THREAD

**Issue by jkelly99** [greenart7c3/Amber#71]
Amber does not connect to the relay or respond to login requests from nostrudl when Push Notifications is selected. It does connect to the relay and function
 when Direct Connection is selected. 

I also notice it does not appear as an entry in the ntfy app that is the phone. Other apps using ntfy, such as Amethyst and Matrix, do.

Amber v1.0.8-free
GrapheneOS latest

**Comment by greenart7c3** [comment]
Do you see any connection issues in the logs at the settings page?

**Comment by jkelly99** [comment]
The log is empty unless I switch to direct connection. 

It seems Amber is not seeing the UnifiedPush provider apps I have running, of which there are two; ntfy and Cheogram. The other apps I have that make use of UP give me the option to select which app to use for UP notifications. Amber does not register with either.

**Comment by jkelly99** [comment]
Wow! Thank you for the quick fix. That did it. I was able to choose ntfy for the notification distributor and connect nostrudl to Amber via the bunker link.

**Comment by ThePhoDit** [comment]
I am facing this exact problem on the latest version. Push notifications with a provider selected does not connect to any relays. Is there any fix other than selecting Direct Connection?

**Comment by greenart7c3** [comment]
What relay are you using?
What nostr app are you trying to use?
What's the notification provider you are using?
Using tor?
Using VPN?
What phone model?
Using a custom os?

**Comment by ThePhoDit** [comment]
> What relay are you using?
The default one: wss://relay.nsec.app

> What nostr app are you trying to use?
habla.news through bunker, but it should be independent, the relays show as offline in the Amber app.

> What's the notification provider you are using?
gCompactUp-Distributor

> Using tor?
Tried with and without.

> Using VPN?
Tried with and without.

> What phone model?
Pixel 6a
> Using a custom os?
GrapheneOS (version 2024080600)

**Comment by greenart7c3** [comment]
The relays don't connect until you get the notification when you are not using the direct connection. My guess is the distributor you are using is not working 
Can you try using ntfy?

**Comment by ThePhoDit** [comment]
I just tried and it does not work with ntfy. No notification nor authorization request reaches the app. Nothing appears on the logs neither.

**Comment by greenart7c3** [comment]
Can you check the logs in the settings page when using your distributor?

**Comment by ThePhoDit** [comment]
There is nothing in the logs according to the timestamps
