### ISSUE TITLE
what is this for?

### ISSUE THREAD

**Issue by wynteryyc** [greenart7c3/Amber#73]
Hi

I installed this but I don't understand what it is for.  For example, I went to creatr.nostr.wine and it didn't sign me into my creatr account. 

what is the expected behaviour of this app?

**Comment by greenart7c3** [comment]
You first need to to create a new app in amber

https://github.com/greenart7c3/Amber/assets/115044884/c01830da-fb71-42e1-a1fc-e4a76fdc81c3

**Comment by wynteryyc** [comment]
thank you! that's awesome. 🙏🙏🙏🏋🏼🏋🏼🏋🏼👍👍👍

Dale Forrest
https://sacredpeak.ink

Sent from Proton Mail Android

-------- Original Message --------

**Comment by wynteryyc** [comment]
delete it
